// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Login struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type NewTime struct {
	TaskID *int `json:"task_id"`
	UserID int  `json:"user_id"`
}

type NewUser struct {
	Email    string `json:"email"`
	Username string `json:"username"`
	Password string `json:"password"`
}

type RefreshTokenInput struct {
	Token string `json:"token"`
}

type UpdateTime struct {
	TimeID int `json:"time_id"`
}

type User struct {
	Email    *string `json:"email"`
	Username string  `json:"username"`
	ID       int64   `json:"id"`
}

type Task struct {
	Name     string  `json:"name"`
	EstHours *int    `json:"est_hours"`
	EstDate  *string `json:"est_date"`
}
